# Generated by Django 5.1.7 on 2025-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_category_alter_playlistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('blog', 'Blog Post')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='video',
            name='blog_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
