# Generated by Django 5.1.6 on 2025-03-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_category_alter_playlistitem_options_and_more'),
        ('videos', '0003_auto_20250326_1731'),
    ]

    operations = [
    ]
