# Generated by Django 5.1.7 on 2025-03-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_merge_0002_add_hls_support_0003_auto_20250326_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_url',
            field=models.URLField(blank=True, help_text='URL to the HLS manifest file (.m3u8)', max_length=500, null=True),
        ),
    ]
