# Generated by Django 5.1.7 on 2025-03-31 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_subscribed_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Moderator'), (3, 'Support Staff')], unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_admins', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes about this admin user'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user has any admin privileges'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.ForeignKey(blank=True, help_text='The admin role assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.adminrole'),
        ),
    ]
