# Generated by Django 5.1.7 on 2025-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('moderation', 'Content Moderation'), ('comment', 'New Comment'), ('like', 'New Like'), ('subscription', 'New Subscription'), ('warning', 'Account Warning'), ('system', 'System Notification'), ('report', 'Content Report')], default='system', max_length=20),
        ),
    ]
